name: Pull Request
on: pull_request

jobs:
  tests:
    runs-on: ubuntu-latest
    name: Run Tests
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Bazel
        uses: bazelbuild/setup-bazelisk@v2

      - name: Run Tests
        run: |
          bazel run //tests:test_image
